books_urls_list_path = 'data/url_list.txt'
books_info_path = 'data/books_info.json'
authors_info_ready_path = 'data/authors_info_ready.json'
authors_info_raw_path = 'data/authors_info_raw.json'
books_texts_path = 'data/books_text.json'
last_grid_search_path = 'models/last_grid_search.pickle'
stats_gird_search_path = 'models/stats_grid_search.pickle'
interface_gird_search_path = 'models/interface_grid_search.pickle'
